production:
  secret_key_base: freelancer
  stripe_publishable_key: 'pk_test_CDDJ2GWWmt2MnA9QBHsMfm6A00J22Fre9T'
  stripe_secret_key: 'sk_test_ZaHswvbougxakuP0ue3xSFXo00pLli1k7ds'
  stripe_public_key: 'pk_test_CDDJ2GWWmt2MnA9QBHsMfm6A00J22Fre9T'
